# Generated by Django 4.0.8 on 2023-01-29 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import unite_compress.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('match_by', models.CharField(choices=[('extension', 'Extension'), ('name', 'File name')], default='extension', max_length=50, verbose_name='Match by')),
                ('match_regex', models.CharField(max_length=200, verbose_name='RegExp to match video file')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled?')),
                ('command', models.TextField(verbose_name='System command to convert video')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=unite_compress.files.models.file_generate_upload_path)),
                ('original_file_name', models.TextField()),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(max_length=255)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
                ('convert_status', models.CharField(choices=[('pending', 'Convert pending'), ('started', 'Convert started'), ('converted', 'Converted'), ('error', 'Not converted due to error')], default='pending', max_length=16, verbose_name='Conversion status')),
                ('converted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Convert time')),
                ('last_convert_msg', models.TextField(blank=True, default='', verbose_name='Message from last converting command')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
