# Generated by Django 4.0.8 on 2023-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_convertingcommand_match_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertingcommand',
            name='mime_regex',
            field=models.CharField(max_length=255, verbose_name='Regex to match mime types'),
        ),
    ]
