# Generated by Django 4.0.8 on 2023-02-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_convertingcommand_mime_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertingcommand',
            name='compression_rate',
            field=models.CharField(choices=[('low', 'Low compression rate'), ('medium', 'Medium compression rate'), ('high', 'High compression rate')], default='medium', max_length=16, verbose_name='compression rate'),
        ),
    ]
