# Generated by Django 4.0.8 on 2023-08-24 09:42

from django.db import migrations, models
import django.db.models.deletion
import unite_compress.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description_alter_course_name_and_more'),
        ('files', '0005_file_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course', verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=unite_compress.files.utils.file_generate_upload_path, verbose_name='File'),
        ),
    ]
